version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-blog}
      POSTGRES_USER: ${POSTGRES_USER:-bloguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-blogpass}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_api
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${POSTGRES_DB:-blog}
      DATABASE_USER: ${POSTGRES_USER:-bloguser}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-blogpass}
      CORS_ORIGIN: "*"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: blog_nginx
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db_data:
